#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ReMax.Resource", IsApplication=true)]

namespace ReMax
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int actionBarBackgroundColor = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int actionBarTextColor = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int selector_tab_text = 2131034114;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int button_blue_normal = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int button_blue_press = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int button_disabled = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int button_red_normal = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int button_red_press = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int check_off = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int check_on = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int circle_blue = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int circle_outline_blue = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int circle_red = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_add_active = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_add_inactive = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_calculator = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_check = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ic_circle_forward = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ic_circle_package = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int ic_delivery = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int ic_dropdown = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int ic_file = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int ic_flash_off = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int ic_flash_on = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int ic_fwd = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int ic_home = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int ic_list_check_blue = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int ic_list_check_red = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int ic_mail_new = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int ic_mail_open = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int ic_menu_calculator = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int ic_menu_delivery = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int ic_menu_file = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int ic_menu_package = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int ic_menu_person = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int ic_menu_pickup = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int ic_menu_service = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int ic_menu_settings = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int ic_menu_sync = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int ic_menu_time = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int ic_more = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int ic_package = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int ic_package_gray = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int ic_person = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int ic_pickup = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int ic_refresh = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int ic_scan_focus = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int ic_service = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int ic_settings = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int ic_sync = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int ic_time = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int Icon = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int launcher_hdpi = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int launcher_mdpi = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int launcher_xhdpi = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int launcher_xxhdpi = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int login_bckg = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int login_logo = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int popup_bckg = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int radio_off = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int radio_on = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int switch_off = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int switch_on = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int tab_bar_background = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int textbox_active = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int textbox_inactive = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int tile_bckg = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int tile_bckg_press = 2130837568;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070005
			public const int btnLogin = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int button1 = 2131165190;
			
			// aapt resource value: 0x7f070004
			public const int inpPassword = 2131165188;
			
			// aapt resource value: 0x7f070002
			public const int inpUserName = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int lblPassword = 2131165187;
			
			// aapt resource value: 0x7f070001
			public const int lblUserName = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int textView1 = 2131165184;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Administration = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int MainMenu = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Menu = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int tabAdministration_txt = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int tabTransport_txt = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int MyTheme = 2131099648;
			
			// aapt resource value: 0x7f060004
			public const int MyTheme_ActionBar_TabText = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int MyTheme_ActionBar_TabView = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int MyTheme_ActionBar_TitleTextStyle = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int MyTheme_ActionBarStyle = 2131099649;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
